### ISSUE TITLE
Add settings menu

### ISSUE THREAD

**Issue by ojgarciab** [AndroidCameraServer/AndroidCameraServer#11]
We need settings menu to avoid hardcoded image resolution, bind port, ect.

**Comment by gsssrao** [comment]
I am interested to work on this. I will post a pull request.

**Comment by ojgarciab** [comment]
Go ahead!

Remember to merge upstream/master to your fork frequently to avoid outdated code on it.

Try to use [Settings](http://developer.android.com/guide/topics/ui/settings.html), it is not necessary any other complex solution. Use a static list of image resolution and later we will use best match.

Best regards!

**Comment by ojgarciab** [comment]
Are you working on it right now? I'll have free time to implement settings right now. If there is not response in 30-60 minutes I'll assign the task myself and code it.

**Comment by ojgarciab** [comment]
I'll start coding right now, I'll add a old styled (fragmentless) preferences activity.

**Comment by gsssrao** [comment]
Sorry, I am working on this. Will post a commit soon. I did not see your comment. I already have implemented the port setting and have made the list for displaying the various camera preview settings. Only a small part is remaining.

**Comment by ojgarciab** [comment]
Ok, I had 3 setting groups:
- ICE settings: protocol (default, tcp and udp), port (> 1024).
- Camera settings: resolution (fixed list), framerate (desired fixed list, possibly not supported, will choose nearest choice).
- System settings: lock screen and wake lock.

Please, add this groups to your code, I'll assign you again the task.

**Comment by gsssrao** [comment]
Ok, completed the port and resolution part. Will add others as well.

**Comment by ojgarciab** [comment]
Great! I'll add support to lock screen, wake lock, framerate, ect when you finish.

We would leave some coding work in a separate issue.

Please, when commit prefix description with "Fix #11" or "Enhancement #11" or similar text to allow git link your commits to this issue.

Thanks.

PS: I must leave this project for a few days, now my priority is to implement navlinkserver jderobot's component. I'll add you write access again.

**Comment by gsssrao** [comment]
I understand the wake lock, but could you explain me lock screen. 

Do you mean a separate lock screen for the app? 

Thanks.
