### ISSUE TITLE
setPreviewsize value can be made better

### ISSUE THREAD

**Issue by gsssrao** [AndroidCameraServer/AndroidCameraServer#13]
@ojgarciab 

In the CameraPreview.java file, first you tried to get the different previw sizes possible and added them to the log cat. But, subsequently you set the preview size to (320, 240). I agree that ICE has a memory limit of 1048576 bytes, but I was able to run the application till the resolution of 800x600 and get the preview on the cameraviewer. So, is there any other reason for setting the resolution to 320x240?

**Comment by gsssrao** [comment]
Sorry, had not seen #11 .

**Comment by ojgarciab** [comment]
Don't worry, I'm working on it on very early stage.

If you want you can implement it taking care of maximum payload limit (based on pixel depth and image resolution).

Remember that NV21 has 2 bytes per pixel, RGB8 has 3, and so on.
