### ISSUE TITLE
Change event listener to class scope in preferences activity

### ISSUE THREAD

**Issue by ojgarciab** [AndroidCameraServer/AndroidCameraServer#17]
Project doesn't work (compile but throws a exception).

Reviewing code I saw this issue and some minor coding style issues.

**Comment by gsssrao** [comment]
Thanks!!

Are there any other things to be implemented? I would love to work on them?

**Comment by ojgarciab** [comment]
Thanks to you too.

Right now the application doesn't work (compile but throws a exception when I click on preferences).

Your version works fine? Are you merging upstream/master repository with your fork to maintain it updated?

**Comment by gsssrao** [comment]
Yes, mine seems to work fine. Will merge upstream/master with fork and check it again.

**Comment by gsssrao** [comment]
Yes, mine is working, checked after merging with upstream as well. I am able to change settings like resolutions and port.

**Comment by ojgarciab** [comment]
When refactoring code (coding styles) the merge could be difficult. I made a mistake, I shouldn't do it before fixing the problem.

If you was updated the merge will success, if not, possibly you was outdated with upstream/master. Could you send me an snapshot of your code (tar.gz or zip) to compare with previous version (before refactoring) to see whats missing?

Thanks.

**Comment by gsssrao** [comment]
The link to older version of repository is : http://goo.gl/T40Yvg

The only difference I have is the target in project properties which is set to android-19. Besides, this I don't see any other difference. I have checked out the code after merging as well and it seems to work on my phone.

**Comment by gsssrao** [comment]
Have a look at #21 . I think that now the project should work.
