### ISSUE TITLE
Change the source code comments into English

### ISSUE THREAD

**Issue by gsssrao** [AndroidCameraServer/AndroidCameraServer#2]
@ojgarciab 
I found that some comments in the java files code are in Spanish. It would be easier for other developers if they were changed into English. I plan on working on this. What do you think?

**Comment by gsssrao** [comment]
@ojgarciab 
I have edited the comments and changed them to English in a fork. I will create a pull request if its ok?

**Comment by ojgarciab** [comment]
Yes, please!. Feel free to translate comments or pushing enhancements!

Sorry my late answer, we are (in Spain) in holidays (passion week).

I'll assign you the issue when you accept the invitation to the team :)
