### ISSUE TITLE
Removing support to android 2.3.3

### ISSUE THREAD

**Issue by ojgarciab** [AndroidCameraServer/AndroidCameraServer#25]
The target of using android API level 10 was using an old mobile (Sony Xperia Neo V) onboard a little robot.

I just upgrade it to ICS, so it is not needed anymore compatibility with older versions because we won't test camera in emulators with older version than ICS.

**Comment by gsssrao** [comment]
@ojgarciab
 Have you already done this or can I do it. 

We can also remove the deprecated setting in camerapreview.java. 

Have you also refactored file structure?

**Comment by ojgarciab** [comment]
I'm working on it. I'll change target to android-15.

Sorry for my late answer, I was eating.

PS: File refactoring will be delayed until milestone 2.0, so we will use this repository until that release.
